# Generated by Django 2.2.16 on 2022-11-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221126_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create',
            new_name='pub_date',
        ),
    ]
