# Generated by Django 2.2.16 on 2022-12-15 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2022, 12, 15, 23, 50, 12, 61425, tzinfo=utc), verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
