# Generated by Django 2.2.16 on 2022-12-16 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_like_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2022, 12, 16, 13, 49, 6, 871249, tzinfo=utc), verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
