# Generated by Django 2.2.16 on 2022-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_follow_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
