# Generated by Django 2.2.16 on 2022-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_readed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='is_readed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='is_readed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_readed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
