# Generated by Django 2.2.16 on 2022-12-17 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_auto_20221217_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_readed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='follow',
            name='is_readed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='like',
            name='is_readed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='post',
            name='is_readed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
