# Generated by Django 2.2.16 on 2022-12-17 21:29

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Вставьте ссылку на видео', null=True, verbose_name='Видео'),
        ),
    ]
