# Generated by Django 2.2.16 on 2022-12-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRead',
        ),
    ]
